### ISSUE TITLE
Themed icons not working in Pixel Experience 12.1 [7.3 Khonsu]

### ISSUE THREAD

**Issue by sanjeevstunner** [Ardjlon/vendor_PixelMod#2]
Expected behaviour: Custom themed icons should be applied to apps like Spotify, YouTube Vanced, Instagram, WhatsApp, Telegram and camera. 

Bug: No visible changes in those above mentioned app's icons. 

![Screenshot_20220419-081748_Pixel Launcher](https://user-images.githubusercontent.com/42514333/163910468-4117151d-6d83-4471-9c20-c7e5d0a3b576.png)

![Screenshot_20220419-095518_Pixel Launcher](https://user-images.githubusercontent.com/42514333/163919960-af3f1d88-91a2-4f4d-94ca-84fcd76fab02.png)

@Ardjlon @saitamasahil

**Comment by Ardjlon** [comment]
Weird, I am using khonsu variant in evox unofficial and works fine here

**Comment by Ardjlon** [comment]
Signed, unsigned? Also you tried with another branch? @sanjeevstunner

**Comment by sanjeevstunner** [comment]
Haven't tried other branches bro 

unsigned, unofficial build

Maybe available in evox BCS it has its own implementation of custom themed icons. It was working for me in PE+ and other ROMs, but not in Regular PE

**Comment by Ardjlon** [comment]
> Haven't tried other branches bro
> 
> unsigned, unofficial build
> 
> Maybe available in evox BCS it has its own implementation of custom themed icons. It was working for me in PE+ and other ROMs, but not in Regular PE

Send dm in telegram, same username as github

**Comment by Ardjlon** [comment]
There was no response, so I proceed to close the thread
